package export

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/rytsh/bag/internal/analyze"
	"github.com/rytsh/bag/internal/graph"
	"github.com/rytsh/bag/internal/model"
)

// ---------------- Cypher ----------------

var cypherIdent = regexp.MustCompile(`[^A-Za-z0-9_]`)

func cypherEscape(s string) string {
	var b strings.Builder

	for _, r := range s {
		if r < ' ' && r != '\t' {
			continue
		}

		b.WriteRune(r)
	}

	return strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`, "\r", `\r`).Replace(b.String())
}

func cypherLabel(raw, fallback string) string {
	c := cypherIdent.ReplaceAllString(raw, "")
	if c == "" || !((c[0] >= 'A' && c[0] <= 'Z') || (c[0] >= 'a' && c[0] <= 'z')) {
		return fallback
	}

	return c
}

func capitalize(s string) string {
	if s == "" {
		return s
	}

	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}

// ToCypher writes a Neo4j import script.
func ToCypher(g *graph.Graph, out string) error {
	lines := []string{"// Neo4j Cypher import - generated by bag", ""}

	for _, n := range g.Nodes() {
		ft := n.FileType
		if ft == "" {
			ft = "unknown"
		}

		lines = append(lines, fmt.Sprintf("MERGE (n:%s {id: '%s', label: '%s'});",
			cypherLabel(capitalize(ft), "Entity"), cypherEscape(n.ID), cypherEscape(n.Label)))
	}

	lines = append(lines, "")

	for _, e := range g.Edges() {
		rel := e.Relation
		if rel == "" {
			rel = "RELATES_TO"
		}

		conf := e.Confidence
		if conf == "" {
			conf = model.Extracted
		}

		lines = append(lines, fmt.Sprintf("MATCH (a {id: '%s'}), (b {id: '%s'}) MERGE (a)-[:%s {confidence: '%s'}]->(b);",
			cypherEscape(e.Source), cypherEscape(e.Target), cypherLabel(strings.ToUpper(rel), "RELATES_TO"), cypherEscape(conf)))
	}

	return graph.WriteFileAtomic(out, []byte(strings.Join(lines, "\n")))
}

// ---------------- GraphML ----------------

var xmlIllegal = regexp.MustCompile("[\x00-\x08\x0b\x0c\x0e-\x1f]")

func xmlSafe(s string) string { return xmlIllegal.ReplaceAllString(s, "") }

type gmlKey struct {
	XMLName  xml.Name `xml:"key"`
	ID       string   `xml:"id,attr"`
	For      string   `xml:"for,attr"`
	AttrName string   `xml:"attr.name,attr"`
	AttrType string   `xml:"attr.type,attr"`
}

type gmlData struct {
	Key   string `xml:"key,attr"`
	Value string `xml:",chardata"`
}

type gmlNode struct {
	ID   string    `xml:"id,attr"`
	Data []gmlData `xml:"data"`
}

type gmlEdge struct {
	Source string    `xml:"source,attr"`
	Target string    `xml:"target,attr"`
	Data   []gmlData `xml:"data"`
}

type gmlGraph struct {
	EdgeDefault string    `xml:"edgedefault,attr"`
	Nodes       []gmlNode `xml:"node"`
	Edges       []gmlEdge `xml:"edge"`
}

type gmlDoc struct {
	XMLName xml.Name `xml:"graphml"`
	XMLNS   string   `xml:"xmlns,attr"`
	Keys    []gmlKey `xml:"key"`
	Graph   gmlGraph `xml:"graph"`
}

// ToGraphML writes a GraphML file (Gephi/yEd).
func ToGraphML(g *graph.Graph, c graph.Communities, out string) error {
	nc := c.NodeCommunity()

	nodeKeys := map[string]string{}
	edgeKeys := map[string]string{}

	typeOf := func(v any) string {
		switch v.(type) {
		case bool:
			return "boolean"
		case int:
			return "long"
		case float64:
			return "double"
		}

		return "string"
	}

	str := func(v any) string {
		switch t := v.(type) {
		case nil:
			return ""
		case string:
			return xmlSafe(t)
		case bool:
			return strconv.FormatBool(t)
		case int:
			return strconv.Itoa(t)
		case float64:
			return strconv.FormatFloat(t, 'g', -1, 64)
		}

		return xmlSafe(fmt.Sprint(v))
	}

	doc := gmlDoc{XMLNS: "http://graphml.graphdrawing.org/xmlns", Graph: gmlGraph{EdgeDefault: "undirected"}}

	for _, n := range g.Nodes() {
		m := graph.NodeMap(n)
		delete(m, "id")

		cid, ok := nc[n.ID]
		if !ok {
			cid = -1
		}

		m["community"] = cid

		gn := gmlNode{ID: xmlSafe(n.ID)}

		for _, k := range sortedKeys(m) {
			if strings.HasPrefix(k, "_") {
				continue
			}

			if _, ok := nodeKeys[k]; !ok {
				nodeKeys[k] = typeOf(m[k])
			}

			gn.Data = append(gn.Data, gmlData{Key: "n_" + k, Value: str(m[k])})
		}

		doc.Graph.Nodes = append(doc.Graph.Nodes, gn)
	}

	for _, e := range g.Edges() {
		m := graph.EdgeMap(e)
		delete(m, "source")
		delete(m, "target")

		ge := gmlEdge{Source: xmlSafe(e.Source), Target: xmlSafe(e.Target)}

		for _, k := range sortedKeys(m) {
			if strings.HasPrefix(k, "_") {
				continue
			}

			if _, ok := edgeKeys[k]; !ok {
				edgeKeys[k] = typeOf(m[k])
			}

			ge.Data = append(ge.Data, gmlData{Key: "e_" + k, Value: str(m[k])})
		}

		doc.Graph.Edges = append(doc.Graph.Edges, ge)
	}

	for _, k := range sortedKeys(nodeKeys) {
		doc.Keys = append(doc.Keys, gmlKey{ID: "n_" + k, For: "node", AttrName: k, AttrType: nodeKeys[k]})
	}

	for _, k := range sortedKeys(edgeKeys) {
		doc.Keys = append(doc.Keys, gmlKey{ID: "e_" + k, For: "edge", AttrName: k, AttrType: edgeKeys[k]})
	}

	raw, err := xml.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}

	return graph.WriteFileAtomic(out, append([]byte(xml.Header), raw...))
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}

	sort.Strings(out)

	return out
}

// ---------------- Wiki ----------------

var unsafeSlug = regexp.MustCompile(`[<>:"/\\|?*#%\x00-\x1f\x7f]`)

func safeFilename(name string, limit int) string {
	s := strings.NewReplacer("/", "-", " ", "_", ":", "-", "(", "", ")", "").Replace(name)
	s = unsafeSlug.ReplaceAllString(s, "_")
	s = strings.Trim(s, ". ")

	if s == "" {
		return "unnamed"
	}

	if r := []rune(s); len(r) > limit {
		s = string(r[:limit])
	}

	return s
}

func mdLink(label string, resolver map[string]string) string {
	text := strings.NewReplacer("[", `\[`, "]", `\]`).Replace(label)
	if slug, ok := resolver[label]; ok {
		return fmt.Sprintf("[%s](%s.md)", text, slug)
	}

	return text
}

// WikiInput bundles wiki inputs.
type WikiInput struct {
	Graph       *graph.Graph
	Communities graph.Communities
	Labels      map[int]string
	Cohesion    map[int]float64
	Gods        []analyze.GodNode
}

// ToWiki writes a markdown wiki (index.md + one article per community and
// god node). Returns the number of articles written.
func ToWiki(in WikiInput, outDir string) (int, error) {
	g := in.Graph

	if len(in.Communities) == 0 {
		return 0, fmt.Errorf("no communities; run `bag extract` first")
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, err
	}

	comms := graph.Communities{}

	for cid, ms := range in.Communities {
		var kept []string

		for _, m := range ms {
			if g.Has(m) {
				kept = append(kept, m)
			}
		}

		if len(kept) > 0 {
			comms[cid] = kept
		}
	}

	label := func(cid int) string {
		if l, ok := in.Labels[cid]; ok {
			return l
		}

		return fmt.Sprintf("Community %d", cid)
	}

	nc := comms.NodeCommunity()
	used := map[string]bool{}
	unique := func(b string) string {
		s := b
		for n := 2; used[strings.ToLower(s)]; n++ {
			s = fmt.Sprintf("%s_%d", b, n)
		}

		used[strings.ToLower(s)] = true

		return s
	}

	resolver := map[string]string{"index": "index"}
	cids := make([]int, 0, len(comms))

	for cid := range comms {
		cids = append(cids, cid)
	}

	sort.Ints(cids)

	commSlug := map[int]string{}

	for _, cid := range cids {
		s := unique(safeFilename(label(cid), 195))
		commSlug[cid] = s

		if _, ok := resolver[label(cid)]; !ok {
			resolver[label(cid)] = s
		}
	}

	type godArt struct{ id, slug string }

	var gods []godArt

	for _, gn := range in.Gods {
		if !g.Has(gn.ID) {
			continue
		}

		s := unique(safeFilename(gn.Label, 195))
		gods = append(gods, godArt{gn.ID, s})

		if _, ok := resolver[gn.Label]; !ok {
			resolver[gn.Label] = s
		}
	}

	produced := map[string]bool{}
	count := 0

	for _, cid := range cids {
		art := communityArticle(g, cid, comms[cid], label, in.Cohesion, nc, resolver)
		f := commSlug[cid] + ".md"

		if err := graph.WriteFileAtomic(filepath.Join(outDir, f), []byte(art)); err != nil {
			return count, err
		}

		produced[f] = true
		count++
	}

	for _, ga := range gods {
		art := godArticle(g, ga.id, label, nc, resolver)
		f := ga.slug + ".md"

		if err := graph.WriteFileAtomic(filepath.Join(outDir, f), []byte(art)); err != nil {
			return count, err
		}

		produced[f] = true
		count++
	}

	if err := graph.WriteFileAtomic(filepath.Join(outDir, "index.md"), []byte(indexMD(g, comms, label, in.Gods, resolver))); err != nil {
		return count, err
	}

	produced["index.md"] = true

	entries, _ := os.ReadDir(outDir)
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".md") && !produced[e.Name()] {
			_ = os.Remove(filepath.Join(outDir, e.Name()))
		}
	}

	return count, nil
}

func communityArticle(g *graph.Graph, cid int, nodes []string, label func(int) string, cohesion map[int]float64,
	nc map[string]int, resolver map[string]string,
) string {
	top := append([]string(nil), nodes...)
	sort.SliceStable(top, func(i, j int) bool { return g.Degree(top[i]) > g.Degree(top[j]) })

	if len(top) > 25 {
		top = top[:25]
	}

	in := map[string]bool{}
	for _, n := range nodes {
		in[n] = true
	}

	cross := map[string]int{}
	conf := map[string]int{}
	seenE := map[*model.Edge]bool{}
	srcs := map[string]bool{}

	for _, n := range nodes {
		if sf := g.Node(n).SourceFile; sf != "" {
			srcs[sf] = true
		}

		for _, nb := range g.Neighbors(n) {
			if c, ok := nc[nb]; ok && c != cid {
				cross[label(c)]++
			}

			e := g.Edge(n, nb)
			if !seenE[e] {
				seenE[e] = true

				cf := e.Confidence
				if cf == "" {
					cf = model.Extracted
				}

				conf[cf]++
			}
		}
	}

	totalE := 0
	for _, v := range conf {
		totalE += v
	}

	if totalE == 0 {
		totalE = 1
	}

	L := []string{"# " + label(cid), ""}

	meta := fmt.Sprintf("%d nodes", len(nodes))
	if c, ok := cohesion[cid]; ok {
		meta += fmt.Sprintf(" · cohesion %.2f", c)
	}

	L = append(L, "> "+meta, "", "## Key Concepts", "")

	for _, n := range top {
		d := g.Node(n)

		src := ""
		if d.SourceFile != "" {
			src = " — `" + d.SourceFile + "`"
		}

		L = append(L, fmt.Sprintf("- **%s** (%d connections)%s", d.Label, g.Degree(n), src))
	}

	if rem := len(nodes) - len(top); rem > 0 {
		L = append(L, fmt.Sprintf("- *... and %d more nodes in this community*", rem))
	}

	L = append(L, "", "## Relationships", "")

	type kc struct {
		k string
		c int
	}

	var cl []kc
	for k, c := range cross {
		cl = append(cl, kc{k, c})
	}

	sort.SliceStable(cl, func(i, j int) bool {
		if cl[i].c != cl[j].c {
			return cl[i].c > cl[j].c
		}

		return cl[i].k < cl[j].k
	})

	if len(cl) == 0 {
		L = append(L, "- No strong cross-community connections detected")
	}

	for i := 0; i < len(cl) && i < 12; i++ {
		L = append(L, fmt.Sprintf("- %s (%d shared connections)", mdLink(cl[i].k, resolver), cl[i].c))
	}

	L = append(L, "")

	if len(srcs) > 0 {
		L = append(L, "## Source Files", "")

		ss := sortedKeys(srcs)
		for i := 0; i < len(ss) && i < 20; i++ {
			L = append(L, "- `"+ss[i]+"`")
		}

		L = append(L, "")
	}

	L = append(L, "## Audit Trail", "")

	for _, c := range []string{model.Extracted, model.Inferred, model.Ambiguous} {
		L = append(L, fmt.Sprintf("- %s: %d (%d%%)", c, conf[c], int(float64(conf[c])/float64(totalE)*100+0.5)))
	}

	L = append(L, "", "---", "", fmt.Sprintf("*Part of the bag knowledge wiki. See %s to navigate.*", mdLink("index", resolver)))

	return strings.Join(L, "\n")
}

func godArticle(g *graph.Graph, id string, label func(int) string, nc map[string]int, resolver map[string]string) string {
	d := g.Node(id)
	L := []string{"# " + d.Label, "", fmt.Sprintf("> God node · %d connections · `%s`", g.Degree(id), d.SourceFile), ""}

	if cid, ok := nc[id]; ok {
		L = append(L, "**Community:** "+mdLink(label(cid), resolver), "")
	}

	nbs := g.Neighbors(id)
	sort.SliceStable(nbs, func(i, j int) bool { return g.Degree(nbs[i]) > g.Degree(nbs[j]) })

	byRel := map[string][]string{}

	for _, nb := range nbs {
		e := g.Edge(id, nb)

		rel := e.Relation
		if rel == "" {
			rel = "related"
		}

		cs := ""
		if e.Confidence != "" {
			cs = " `" + e.Confidence + "`"
		}

		byRel[rel] = append(byRel[rel], mdLink(g.Node(nb).Label, resolver)+cs)
	}

	L = append(L, "## Connections by Relation", "")

	for _, rel := range sortedKeys(byRel) {
		ts := byRel[rel]
		L = append(L, "### "+rel)

		for i := 0; i < len(ts) && i < 20; i++ {
			L = append(L, "- "+ts[i])
		}

		if len(ts) > 20 {
			L = append(L, fmt.Sprintf("- *…and %d more `%s` connection(s) not listed (lowest-degree first to go)*", len(ts)-20, rel))
		}

		L = append(L, "")
	}

	L = append(L, "---", "", fmt.Sprintf("*Part of the bag knowledge wiki. See %s to navigate.*", mdLink("index", resolver)))

	return strings.Join(L, "\n")
}

func indexMD(g *graph.Graph, comms graph.Communities, label func(int) string, gods []analyze.GodNode, resolver map[string]string) string {
	L := []string{
		"# Knowledge Graph Index", "",
		"> Auto-generated by bag. Start here — read community articles for context, then drill into god nodes for detail.", "",
		fmt.Sprintf("**%d nodes · %d edges · %d communities**", g.NumNodes(), g.NumEdges(), len(comms)), "",
		"---", "", "## Communities", "(sorted by size, largest first)", "",
	}

	cids := make([]int, 0, len(comms))
	for cid := range comms {
		cids = append(cids, cid)
	}

	sort.SliceStable(cids, func(i, j int) bool {
		if len(comms[cids[i]]) != len(comms[cids[j]]) {
			return len(comms[cids[i]]) > len(comms[cids[j]])
		}

		return cids[i] < cids[j]
	})

	for _, cid := range cids {
		L = append(L, fmt.Sprintf("- %s — %d nodes", mdLink(label(cid), resolver), len(comms[cid])))
	}

	L = append(L, "")

	if len(gods) > 0 {
		L = append(L, "## God Nodes", "(most connected concepts — the load-bearing abstractions)", "")

		for _, gn := range gods {
			L = append(L, fmt.Sprintf("- %s — %d connections", mdLink(gn.Label, resolver), gn.Degree))
		}

		L = append(L, "")
	}

	L = append(L, "---", "", "*Generated by [bag](https://github.com/rytsh/bag)*")

	return strings.Join(L, "\n")
}
